Catch FFmpeg error messages

diff --git a/make_directives b/make_directives
--- a/make_directives
+++ b/make_directives
@@ -32,10 +32,12 @@ stage: all LICENSE.txt myabcs.png cleanstage
 			if test "${VORBIS}"; then \
 				target_ogg="$${target_dir}/$$(basename $${SND} | sed -e 's|\.flac|\.oga|')"; \
 				echo "'$${SND}' -> '$${target_ogg}'"; \
-				ffmpeg -hide_banner -loglevel panic -y -i "$${SND}" -c:a libvorbis -b:a 96k -ar 44100 "$${target_ogg}"; \
-				if test $$? -ne 0; then \
-					echo -e "\nError converting PCM to Vorbis data. Is FFmpeg installed?"; \
-					exit 1; \
+				err=$$(ffmpeg -hide_banner -y -i "$${SND}" -c:a libvorbis -b:a 96k -ar 44100 "$${target_ogg}" 2>&1 > /dev/null); \
+				err_id=$$?; \
+				if test $${err_id} -ne 0; then \
+					echo -e "\nError converting FLAC to Vorbis data. Is FFmpeg installed?"; \
+					echo -e "\nCommand output:\n$${err}\n"; \
+					exit $${err_id}; \
 				fi; \
 			else \
 				install -vm 0644 "$${SND}" "$${target_dir}"; \
